death-message: "§cʏᴏᴜ ʜᴀᴠᴇ ᴅɪᴇᴅ ᴀɴᴅ ʜᴀᴠᴇ ʙᴇᴇɴ ᴅᴇᴀᴛʜᴋɪᴄᴋᴇᴅ ꜰʀᴏᴍ ᴛʜᴇ ѕᴇʀᴠᴇʀ!"
prefix: "§8[§x§6§E§4§7§A§0ᴜ§x§6§E§4§7§A§0ɴ§x§6§9§4§6§9§Dѕ§x§6§4§4§5§9§Aᴛ§x§5§E§4§3§9§7ᴀ§x§5§9§4§2§9§4ʙ§x§5§4§4§1§9§1ʟ§x§4§F§4§0§8§Eᴇ§x§4§9§3§E§8§Bѕ§x§4§4§3§D§8§8ᴍ§x§4§4§3§D§8§8ᴘ§8] "
resource-pack:
  url: "https://minepack.fr/pack/ecd41192-136f-4b61-a681-106daf75634f"
  sha1: "dbe9bf8a4b6f5ac012de87a9947f231eb7bfe354"
  id: "ecd41192-136f-4b61-a681-106daf75634f"
  prompt: "ᴛʜᴇ ѕᴇʀᴠᴇʀ ʀᴇᴄᴏᴍᴍᴇɴᴅѕ ʏᴏᴜ ᴜѕᴇ ᴛʜᴇ ᴘʀᴏᴠɪᴅᴇᴅ ʀᴇѕᴏᴜʀᴄᴇ ᴘᴀᴄᴋ ᴛᴏ ɪᴍᴘʀᴏᴠᴇ ʏᴏᴜʀ ᴇхᴘᴇʀɪᴇɴᴄᴇ ᴏɴ ᴛʜᴇ ѕᴇʀᴠᴇʀ."
auto-update: true
render-distance:
  enabled: true
  min: 8
  max: 18
  player-max-threshold: 100
features:
  deathkick: true
  netheriteban: false
  maceban: false
  macenerf: false
